version: "3.9"

services:

  go_postgres_db:
    container_name: Drive-Go-postgres
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: Drive-gO
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - drive_network

  go_mongo_db:
    container_name: Drive-Go-mongo
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    networks:
      - drive_network

volumes:
  pgdata: {}

networks:
  drive_network:
    driver: bridge
